DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nick_name VARCHAR(50) NOT NULL DEFAULT '',
  email VARCHAR(50) NOT NULL DEFAULT '',
  password VARCHAR(50) NOT NULL DEFAULT '',
  is_active TINYINT(4) NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

INSERT INTO `user`(nick_name, email, password) VALUES('toy张', '23948@qq.com', '123456asd');
